### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by EmiOnGit** [viridia/panoply#1]
Just saw your water showcase in the bevy discord and it looks great! :)

Sadly, this project has no license so it's unknown if it's fine to take inspiration from your code (which I assume is fine since you uploaded it publicly anyway).

I would suggest you add a LICENSE to your project!

**Comment by viridia** [comment]
I'm in the middle of a large refactor and things are kind of broken at the moment. I'll think about licenses once things are working again. For now I will leave this open. And thanks for bringing this to my attention!

**Comment by viridia** [comment]
I've added the license files.
